[package]
name = "cram"
version = "0.1.0"
edition = "2021"
authors = ["J. L. Hay <mail@jordanhay.com>"]
description = "Command line Rust Account Manager"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/JHay0112/cram"

[dependencies]
